name: pomapf-eval
use_wandb: True
environment:
  name: POMAPF-v0

  grid_config:
    max_episode_steps: 512
    map_name:
      grid_search: [ 'sc1-TheFrozenSea', 'sc1-TheHighway', 'sc1-TheatreofWar', 'sc1-ThinIce', 'sc1-Tribes', 'sc1-Triskelion', 'sc1-Turbo', 'sc1-Typhoon', 'sc1-ValleyofRe', 'sc1-WarpGates', 'sc1-WatersEdge', 'sc1-WaypointJunction', 'sc1-WheelofWar', 'sc1-WinterConquest',
                     'street-Shanghai_0', 'street-Shanghai_1', 'street-Shanghai_2', 'street-Sydney_0', 'street-Sydney_1', 'street-Sydney_2',
                     'wc3-ScorchedBasin', 'wc3-Stromguarde', 'wc3-TheCrucible', 'wc3-TheGlaive', 'wc3-TranquilPaths',
                     'mazes-s40_wc4_od30', 'mazes-s41_wc5_od50', 'mazes-s42_wc7_od30', 'mazes-s43_wc2_od45', 'mazes-s44_wc2_od30', 'mazes-s45_wc4_od55', 'mazes-s46_wc2_od55', 'mazes-s47_wc2_od25', 'mazes-s48_wc3_od65', 'mazes-s49_wc2_od50',
                     'random-s40_d0.15', 'random-s41_d0.2', 'random-s42_d0.25', 'random-s43_d0.3', 'random-s44_d0.35', 'random-s45_d0.15', 'random-s46_d0.2', 'random-s47_d0.25', 'random-s48_d0.3', 'random-s49_d0.35' ]

    num_agents:
      grid_search: [ 50, 100, 150, 200, 250, 300]
    seed:
      grid_search: [ 0, 1, 2, 3, 4, 5]
algo:
  name: LSwitcher
  num_process: 6
  min_consequence_steps:
    grid_search: [1, 25, 50, 75, 100]

results_views:
  - { type: tabular, drop_keys: [ seed, flowtime, makespan, num_agents ], table_format: latex_booktabs }
  - { type: tabular, drop_keys: [ seed, flowtime, makespan, map_name ], print_results: True }
  - { type: plot, x: num_agents, y: CSR }
  - { type: plot, x: num_agents, y: ISR }
  - { type: plot, x: min_consequence_steps, y: CSR }
  - { type: plot, x: min_consequence_steps, y: ISR }
