name: pomapf-eval
use_wandb: True
environment:
  name: POMAPF-v0
  grid_config:
    max_episode_steps: 512
    map_name:
      grid_search: [ 'sc1-TheFrozenSea', 'sc1-TheHighway', 'sc1-TheatreofWar', 'sc1-ThinIce', 'sc1-Tribes', 'sc1-Triskelion', 'sc1-Turbo', 'sc1-Typhoon', 'sc1-ValleyofRe', 'sc1-WarpGates', 'sc1-WatersEdge', 'sc1-WaypointJunction', 'sc1-WheelofWar', 'sc1-WinterConquest',
                     'street-Shanghai_0', 'street-Shanghai_1', 'street-Shanghai_2', 'street-Sydney_0', 'street-Sydney_1', 'street-Sydney_2',
                     'wc3-ScorchedBasin', 'wc3-Stromguarde', 'wc3-TheCrucible', 'wc3-TheGlaive', 'wc3-TranquilPaths',
                     'mazes-s40_wc4_od30', 'mazes-s41_wc5_od50', 'mazes-s42_wc7_od30', 'mazes-s43_wc2_od45', 'mazes-s44_wc2_od30', 'mazes-s45_wc4_od55', 'mazes-s46_wc2_od55', 'mazes-s47_wc2_od25', 'mazes-s48_wc3_od65', 'mazes-s49_wc2_od50',
                     'random-s40_d0.15', 'random-s41_d0.2', 'random-s42_d0.25', 'random-s43_d0.3', 'random-s44_d0.35', 'random-s45_d0.15', 'random-s46_d0.2', 'random-s47_d0.25', 'random-s48_d0.3', 'random-s49_d0.35' ]
    num_agents:
      grid_search: [ 50, 100, 150, 200, 250, 300, 350, 450, 500 ]
    seed:
      grid_search: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, ]

algo:
  grid_search:
    - { name: HSwitcher, learning: { name: APPO, path_to_weights: "results/ma" }, num_process: 10 }
    - { name: APPO, path_to_weights: "results/ma", num_process: 10 }
    - { name: ASwitcher, learning: { name: APPO, path_to_weights: "results/ma" }, num_process: 10 }
    - { name: A*, max_planning_steps: 10000, num_process: 40 }
results_views:
  - { type: tabular, drop_keys: [ seed, flowtime, makespan, num_agents ], table_format: latex_booktabs }
  - { type: tabular, drop_keys: [ seed, flowtime, makespan, map_name ], print: True }
  - { type: plot, x: num_agents, y: CSR }
  - { type: plot, x: num_agents, y: ISR }
  - { type: plot, x: num_agents, y: makespan }
  - { type: plot, x: num_agents, y: rl_used }


