name: pomapf-train-gm-ablation-v5

global_settings:
  use_wandb: True
experiment_settings:
  save_every_sec: 120
  encoder_custom: pogema_residual
  train_for_env_steps: 30000000
async_ppo:
  experiment_summaries_interval: 20
  ppo_epochs: 1
  batch_size: 1024
  max_grad_norm: 5.0
  num_workers: 12
  num_envs_per_worker: 16
  with_vtrace: False
  max_policy_lag: 100
  exploration_loss_coeff: 0.01

  with_pbt: False
  use_rnn: True

environment:
  name: POMAPF-v0
  grid_memory_obs_radius:
    grid_search: [null, 5 ]
  grid_config:
    map_name: '(wc3-[A-P]|sc1-[A-S]|sc1-TaleofTwoCities|street-[A-P]|mazes-s[0-9]_|mazes-s[1-3][0-9]_|random-s[0-9]_|random-s[1-3][0-9]_)'
    max_episode_steps: 512
    obs_radius:
      grid_search: [1, 2, 3, 4 ]
    num_agents: 1
