name: pomapf-v2-debug

global_settings:
  use_wandb: False
experiment_settings:
  save_every_sec: 120
  encoder_custom: pogema_residual
  train_for_env_steps: 10000000
async_ppo:
  traj_buffers_excess_ratio: 2
  experiment_summaries_interval: 20
  ppo_epochs: 1
  batch_size: 1024
  use_rnn: True
  max_grad_norm: 0.0
  num_workers: 2
  num_envs_per_worker: 2


environment:
  name: POMAPF-v0
  grid_config:
    map_name: '(wc3-[A-P]|sc1-[A-S]|sc1-TaleofTwoCities|street-[A-P]|mazes-s[0-9]_|mazes-s[1-3][0-9]_|random-s[0-9]_|random-s[1-3][0-9]_)'
    max_episode_steps: 256
    obs_radius: 5
    num_agents: 16